-- Carga la carta de Cantina Dos Santos (360 ítems) en carta_items.
-- Correr DESPUÉS de create_eventos_carta.sql.
-- Seguro de correr más de una vez: si un ítem (misma categoría + nombre) ya existe
-- en el punto, actualiza su descripción y precio en vez de duplicarlo.

insert into public.carta_items (location_id, categoria, nombre, descripcion, precio, orden)
select l.id, v.categoria, v.nombre, v.descripcion, v.precio, v.orden
from public.locations l
cross join (values
('AGUARDIENTE', 'BT.AMARILLO MANZANARES', null, 270000, 1),
('AGUARDIENTE', 'BT.ANTIOQUEÑO AZUL', null, 250000, 2),
('AGUARDIENTE', 'BT.ANTIOQUEÑO ROJO', null, 250000, 3),
('AGUARDIENTE', 'BT.ANTIOQUEÑO VERDE', null, 290000, 4),
('AGUARDIENTE', 'BT.BLANCO DEL VALLE AZUL', null, 263000, 5),
('AGUARDIENTE', 'BT.BLANCO DEL VALLE ROJO', null, 263000, 6),
('AGUARDIENTE', 'MD. AMARILLO MANZANAREZ', null, 180000, 7),
('AGUARDIENTE', 'MD. ANTIOQUEÑO AZUL', null, 160000, 8),
('AGUARDIENTE', 'MD. ANTIOQUEÑO ROJO', null, 160000, 9),
('AGUARDIENTE', 'MD. BLANCO DEL VALLE AZUL', null, 160000, 10),
('AGUARDIENTE', 'MD. BLANCO DEL VALLE ROJO', null, 160000, 11),
('AGUARDIENTE', 'TG.AMARILLO MANZANARES', null, 30000, 12),
('AGUARDIENTE', 'TG.ANTIOQUEÑO AZUL', null, 27000, 13),
('AGUARDIENTE', 'TG.ANTIOQUEÑO ROJA', null, 21000, 14),
('AGUARDIENTE', 'TG.ANTIOQUEÑO VERDE', null, 21000, 15),
('AGUARDIENTE', 'TG.BLANCO DEL VALLE AZUL', null, 27000, 16),
('AGUARDIENTE', 'TG.BLANCO DEL VALLE ROJO', null, 27000, 17),
('BEBIDAS SIN LICOR', 'AGUA HATSU', null, 11000, 18),
('BEBIDAS SIN LICOR', 'AGUA HATSU CON GAS', null, 11000, 19),
('BEBIDAS SIN LICOR', 'AGUA MINERAL EVIAN', null, 23000, 20),
('BEBIDAS SIN LICOR', 'AGUA PERRIER', null, 23000, 21),
('BEBIDAS SIN LICOR', 'AGUA VOSS', null, 23000, 22),
('BEBIDAS SIN LICOR', 'AGUA VOSS CARBONATADA', null, 23000, 23),
('BEBIDAS SIN LICOR', 'CANADA DRY', null, 11000, 24),
('BEBIDAS SIN LICOR', 'COCACOLA REGULAR', null, 11000, 25),
('BEBIDAS SIN LICOR', 'COCACOLA ZERO', null, 11000, 26),
('BEBIDAS SIN LICOR', 'CUATRO', null, 11000, 27),
('BEBIDAS SIN LICOR', 'COCTEL SIN LICOR', null, 25000, 28),
('BEBIDAS SIN LICOR', 'GATORLYTE', null, 17000, 29),
('BEBIDAS SIN LICOR', 'HATSU AMARILLO', null, 13000, 30),
('BEBIDAS SIN LICOR', 'HATSU BLANCO', null, 13000, 31),
('BEBIDAS SIN LICOR', 'HATSU LILA', null, 13000, 32),
('BEBIDAS SIN LICOR', 'HATSU NEGRO', null, 13000, 33),
('BEBIDAS SIN LICOR', 'RED BULL', null, 18000, 34),
('BEBIDAS SIN LICOR', 'RED BULL FREE', null, 18000, 35),
('BEBIDAS SIN LICOR', 'RED BULL SANDIA', null, 18000, 36),
('BEBIDAS SIN LICOR', 'SODA', null, 11000, 37),
('SODAS Y JUGOS', 'SODA FRUTOS ROJOS', 'Soda refrescante a base de syrup de frutos rojos y bretaña.', 17500, 38),
('SODAS Y JUGOS', 'SODA LYCHES', 'Soda refrescante a base de syrup de lyches y bretaña.', 17500, 39),
('SODAS Y JUGOS', 'SODA MARACUYA GINGER', 'Soda refrescante a base de syrup de maracuya y bretaña.', 17500, 40),
('SODAS Y JUGOS', 'J NARANJA PINA', null, 14000, 41),
('SODAS Y JUGOS', 'LIMONADA DE COCO', null, 14000, 42),
('SODAS Y JUGOS', 'LIMONADA NATURAL', null, 14000, 43),
('CERVEZAS', 'DRAFT TRES CORDILLERAS MONA', null, 18000, 44),
('CERVEZAS', 'DRAFT TRES CORDILLERAS NEGRA', null, 18000, 45),
('CERVEZAS', 'HEINEKEN', null, 18000, 46),
('CERVEZAS', 'PA MACHO', 'Cerveza de la casa PA MACHOS con Sol, una mezcla de sangrita, Tequila cazadores reposado y cítricos.', 33000, 47),
('CERVEZAS', 'SOL', null, 18000, 48),
('CERVEZAS', '3 CORDILLERAS MULATA', null, 18000, 49),
('CERVEZAS', '3 CORDILLERAS NEGRA', null, 18000, 50),
('CERVEZAS', '3 CORDILLERAS ROSADA', null, 18000, 51),
('COCTELERIA CLASICA', 'BLOODY MARY', 'Perfil: Picante-salado. Smirnoff red No.21, jugo de tomate, salsa worcestershire, zumo de limón, tres dash de tabasco, pizca de sal y pimienta. Michelado con tajín', 45000, 52),
('COCTELERIA CLASICA', 'CAIPIROSKA', 'Perfil: Cítrico-equilibrado. Smirnoff red No.21, zumo de limón, almibar simple. Michelado con azúcar', 45000, 53),
('COCTELERIA CLASICA', 'CARAJILLO', 'Perfil: Dulce-cremoso Licor 43, espresso.', 42000, 54),
('COCTELERIA CLASICA', 'COSMOPOLITAN', 'Perfil: Cítrico-equilibrado. Smirnoff red No.21, Cointreau, finestcall de cranberry y zumo de limón. Decorado con twist de limón', 45000, 55),
('COCTELERIA CLASICA', 'CUBA LIBRE', 'Perfil: Suave-equilibrado. Bacardí Carta Blanca, zumo de limón y coca-cola.', 45000, 56),
('COCTELERIA CLASICA', 'DRY MARTINI', 'Perfil: Complejo-amargo. Tanqueray london, Martini Dry y aceitunas.', 51000, 57),
('COCTELERIA CLASICA', 'ESPRESSO MARTINI', 'Perfil: Dulce-cremoso. Smirnoff red No.21, tia maria Licor de Café, espresso y almibar', 45000, 58),
('COCTELERIA CLASICA', 'LONG ISLAND ICE TEA', 'Perfil:Dulce-equilibrado Tanqueray London ,Smirnoff red No.21, Bacardí Carta Blanca, Cazadores Reposado, Cointreau, almibar simple y zumo de limón', 48000, 59),
('COCTELERIA CLASICA', 'LYCHEE MARTINI', 'Perfil: Dulce-equilibrado. Smirnoff red No.21, almibar de lychee y zumo de limón', 45000, 60),
('COCTELERIA CLASICA', 'MANHATTAN', 'Perfil: Dulce-intenso. Bulleit buorbon, Martini Rosso y gotas amargas. Decorado con twist de limón.', 51000, 61),
('COCTELERIA CLASICA', 'MARGARITA SHAKE', 'Perfil: Citrico-equilibrado. Patrón Silver, Cointreau, zumo de limón y almibar. 48.000', 48000, 62),
('COCTELERIA CLASICA', 'MEZCAL MULE', 'Perfil: Ahumado-equilibrado. Mezcal union, zumo de limón, almíbar de jengibre y Mil976 ginger beer.', 52000, 63),
('COCTELERIA CLASICA', 'MOJITO', 'Perfil: Suave-equilibrado. Bacardí Carta Blanca, hierbabuena, zumo de limón, almíbar simple y soda Bretaña', 45000, 64),
('COCTELERIA CLASICA', 'MOSCOW MULE', 'Perfil: Citrico-picante. Smirnoff red No.21 zumo de limón, almibar de jengibre y Mil976 gingerbeer.', 48000, 65),
('COCTELERIA CLASICA', 'NEGRONI', 'Perfil: Complejo-intenso Tanqueray london, Martini Rosso, Campari. Decorado con twist de naranja', 48000, 66),
('COCTELERIA CLASICA', 'NEW YORK SOUR', 'Perfil: Equilibrado-sedoso. Bulleit bourbon, zumo de limón, almíbar simple, agente emulsionante. Terminado con capa de vino Santa Carolina Carmenere.', 45000, 67),
('COCTELERIA CLASICA', 'OLD FASHIONED', 'Perfil: Cálido-dulce. Bulleit bourbon, gotas amargas y almíbar simple.', 48000, 68),
('COCTELERIA CLASICA', 'PALOMA BY PATRON', 'Perfil: Equilibrado-refrescante. Patrón Silver, zumo de limón, almíbar y Mil976 de toronja. Michelado con tajín.', 45000, 69),
('COCTELERIA CLASICA', 'PALOMA MEZCAL', 'Perfil: Equilibrado-refrescante. Mezcal union, zumo de limón, almíbar y Mil976 de toronja. Michelado con tajín.', 52000, 70),
('COCTELERIA CLASICA', 'PENICILLIN', 'Perfil: Equilibrado-picoso. Black label, almíbar de jengibre, zumo de limón.', 45000, 71),
('COCTELERIA CLASICA', 'WHISKY SOUR', 'Perfil: Equilibrado-sedoso. Bulleit bourbon, zumo de limon, almibar simple, agente emulsionante.', 45000, 72),
('COCTELERIA SIGNATURE', 'BUCHANITAS TONIC', 'Buchanans 12 Años, MIL 976 OCEAN', 48000, 73),
('COCTELERIA SIGNATURE', 'ESPIRITU NAHUAL - LOBO', 'Perfil: Ahumado-picante. Mezcal 400 conejos, jack daniels, mix de cítricos, infusion de hibiscus y reducción de piña, fresa y chile rocotto', 51000, 74),
('COCTELERIA SIGNATURE', 'FUEGO TROPICAL', 'Una mezcla tropical y con mucho carácter. Smirnoff Tamarindo, mix de piña y maracuyá, limón y miel de chiles, terminado con espuma de tamarindo salada y tajín. Tropical, ácido y con un toque picante.', 48000, 75),
('COCTELERIA SIGNATURE', 'HERENCIA', 'Perfil: Refrescante - Frutal.', 35000, 76),
('COCTELERIA SIGNATURE', 'LA MANO', 'Viche herencia Guapireña, cordial de grosellas, zumo de grosellas, finalizado con Mil976 de toronja, acompañado de grosellas bañadas en sal, limón y tajin.', 47000, 77),
('COCTELERIA SIGNATURE', 'LEYENDA MAYA AGUILA', 'Perfil: Floral Refrescante. Tanqueray london, Smirnoff red No.21, limoncello artesanal, puré de lulo y lambrusco piccini rosado', 51000, 78),
('COCTELERIA SIGNATURE', 'MARGARITA COCO', 'Perfil: Dulce-cremoso. Don Julio Blanco, triple sec, pulpa de coco y zumo de limón.', 48000, 79),
('COCTELERIA SIGNATURE', 'MARGARITA FROZEN', 'Perfil: Cítrico-equilibrado. Cazadores reposado, triple sec, zumo de limón y almíbar.', 48000, 80),
('COCTELERIA SIGNATURE', 'MARGARITA FRUTOS ROJOS', 'Perfil: Dulce-refrescante. Cazadores Reposado, triple sec, zumo de limón y reducción de frutos rojos.', 48000, 81),
('COCTELERIA SIGNATURE', 'MARGARITA LULO', 'Perfil: Acido-Refrescante. Cazadores Reposado, Triplesec, zumo de lulo y zumo de limón.', 48000, 82),
('COCTELERIA SIGNATURE', 'MARGARITA MARACUYA', 'Perfil: Ácido-refrescante. Cazadores Reposado, triple sec, zumo de limón y almíbar de maracuyá.', 48000, 83),
('ESPUMANTES', 'BT.BRUT ROSE CHANDON', null, 260000, 84),
('ESPUMANTES', 'BT.CHANDON EXTRA BRUT', null, 250000, 85),
('ESPUMANTES', 'BT.CINZANO TO SPRIT', null, 242000, 86),
('ESPUMANTES', 'BT.DOM PERIGNON', null, 3200000, 87),
('ESPUMANTES', 'BT.JP ICE BLANCO', null, 200000, 88),
('ESPUMANTES', 'BT.MOET ICE', null, 980000, 89),
('ESPUMANTES', 'BT.MOET&CHANDON IMPERIAL', null, 910000, 90),
('ESPUMANTES', 'BT.MOET&CHANDON IMPERIAL ROSE', null, 1100000, 91),
('ESPUMANTES', 'BT.VEUVE CLICOUT BRUT', null, 930000, 92),
('GINEBRAS', 'BT.BOMBAY SAPHIRE', null, 360000, 93),
('GINEBRAS', 'BT.BULLDOG', null, 480000, 94),
('GINEBRAS', 'BT.HENDRICKS', null, 530000, 95),
('GINEBRAS', 'BT.TANQUERAY LONDON', null, 420000, 96),
('GINEBRAS', 'BT.TANQUERAY RANGPUR', null, 420000, 97),
('GINEBRAS', 'BT.TANQUERAY TEN', null, 610000, 98),
('GINEBRAS', 'TG.BOMBAY SHAPIRE', null, 35000, 99),
('GINEBRAS', 'TG.BULLDOG', null, 39000, 100),
('GINEBRAS', 'TG.HENDRICKS', null, 53000, 101),
('GINEBRAS', 'TG.TANQUERAY LONDON', null, 40000, 102),
('GINEBRAS', 'TG.TANQUERAY RANGPUR', null, 44000, 103),
('GINEBRAS', 'TG.TANQUERAY TEN', null, 55000, 104),
('MEZCALES', 'BT.400 CONEJOS', null, 560000, 105),
('MEZCALES', 'BT.AMORES', null, 567000, 106),
('MEZCALES', 'BT.CONTRALUZ', null, 690000, 107),
('MEZCALES', 'BT.MONTELOBOS', null, 590000, 108),
('MEZCALES', 'BT.SIETE MISTERIOS', null, 570000, 109),
('MEZCALES', 'BT.UNION', null, 494000, 110),
('MEZCALES', 'TG.400 CONEJOS', null, 44800, 111),
('MEZCALES', 'TG.AMORES', null, 45000, 112),
('MEZCALES', 'TG.CONTRALUZ', null, 55200, 113),
('MEZCALES', 'TG.MONTELOBOS', null, 41200, 114),
('MEZCALES', 'TG.SIETE MISTERIOS', null, 45600, 115),
('MEZCALES', 'TG.UNION', null, 39500, 116),
('MOCKTAILS', 'AURORA DEL ARENAL', 'Jugoso y especiado. Durazno canela, miel y hierbabuena con un final burbujeante de jengibre.', 27000, 117),
('MOCKTAILS', 'BRISA DE CHAPALA', 'Limpio y refrescante. Sandía y pepino con romero y cítricos, ligero y revitalizante.', 27000, 118),
('MOCKTAILS', 'RIVERA DEL SOL', 'Cremoso y tropical. Piña y coco con maracuyá y un toque cítrico refrescante.', 27000, 119),
('OTROS LICORES', 'BT.BAILEYS', null, 280000, 120),
('OTROS LICORES', 'BT.COINTREAU', null, 338000, 121),
('OTROS LICORES', 'BT.DISARONNO', null, 336000, 122),
('OTROS LICORES', 'BT.JAGGEMAISTER', null, 270000, 123),
('OTROS LICORES', 'BT.LIMONCHELLO', null, 389000, 124),
('OTROS LICORES', 'DECANTER COINTREAU', null, 90000, 125),
('OTROS LICORES', 'DECANTER TRIPLE SEC', null, 39000, 126),
('OTROS LICORES', 'TG.APEROL', null, 23000, 127),
('OTROS LICORES', 'TG.BAILEYS', null, 28000, 128),
('OTROS LICORES', 'TG.CAMPARI', null, 25000, 129),
('OTROS LICORES', 'TG.COINTREAU', null, 30000, 130),
('OTROS LICORES', 'TG.DISARONNO', null, 27000, 131),
('OTROS LICORES', 'TG.JAGGERMASTER', null, 27000, 132),
('OTROS LICORES', 'TG.LICOR 43', null, 30000, 133),
('OTROS LICORES', 'TG.LICOR DE CAFE', null, 20000, 134),
('OTROS LICORES', 'TG.LIMONCHELLO', null, 32000, 135),
('OTROS LICORES', 'TG.PISCO', null, 25000, 136),
('OTROS LICORES', 'TG.TRIPLE SEC', null, 10000, 137),
('OTROS LICORES', 'TG.VERMOUTH ROSSO', null, 17000, 138),
('RON', 'BT.BACARDI BLANCO', null, 260000, 139),
('RON', 'BT.BACARDI 8 AÑOS', null, 380000, 140),
('RON', 'BT.BACARDI AÑEJO', null, 260000, 141),
('RON', 'BT.CALDAS 8 AÑOS', null, 310000, 142),
('RON', 'BT.FLOR DE CAÑA ORO 12', null, 410000, 143),
('RON', 'BT.MEDELLIN 8 AÑOS', null, 299000, 144),
('RON', 'BT.SANTA TERESA 1796', null, 580000, 145),
('RON', 'BT.ZACAPA 23', null, 700000, 146),
('RON', 'MD. MEDELLIN 8 AÑOS', null, 299000, 147),
('RON', 'TG.BACARDI BLANCO', null, 24000, 148),
('RON', 'TG.BACARDI 8 AÑOS', null, 30000, 149),
('RON', 'TG.BACARDI AÑEJO', null, 26000, 150),
('RON', 'TG.CALDAS 8 AÑOS', null, 24800, 151),
('RON', 'TG.FLOR DE CAÑA ORO 12', null, 35000, 152),
('RON', 'TG.MEDELLIN 8 AÑOS', null, 24000, 153),
('RON', 'TG.SANTA TERESA 1796', null, 48000, 154),
('RON', 'TG.ZACAPA 23', null, 49000, 155),
('SANGRIA', 'JARRA SANGRIA ROSE', 'Floral, cítrica y provocadora. Lavanda y jamaica se mezclan con piña fresca, lambrusco piccini rosado, Aperol y ginebra Tanqueray london, burbujeante de mil 976 de toronja y frutas tropicales como maracuyá, fresa y toronja', 220000, 156),
('SANGRIA', 'JARRA SANGRIA TINTO', 'Intensa, pícara y con un cuerpo fuerte. Tamarindo y miel de chiles se funden con naranja, lambrusco piccini tinto. cazadores reposado y Cointreau, coronada con ginger beer mil 976 y frutas exóticas como lo son el mango con Tajín, naranja y piña', 220000, 157),
('SPRITZ', 'CASCADA CITRINA', 'Fresco y chispeante. Villa massa limoncello, cinzano to spritz y carambolo con frambuesa, ligero y deliciosamente ácido.', 42000, 158),
('SPRITZ', 'HUERTO ANTIGUO', 'Shrub de manzana verde y romero, Jack Daniel´s apple, jerez oloroso, cinzano to sprits y soda. El huerto donde encuentras la manzana a través del shrub frutal y punzante. La frescura y el brillo en el jack daniels apple, jerez el alma antigua de la bebida a través del tiempo que pasa en barricas solera.', 42000, 159),
('SPRITZ', 'OCASO DORADO', 'Licor 43, cold brew (café devoción) con cascaras de naranja y limón, zumo de naranja, cinzano to sprits y tónica MIL 976 indi. Los colores del atardecer y los ingredientes que componen este spritz balanceado, fresco y especiado', 42000, 160),
('SPRITZ', 'ROSAL DE BAJIO', 'St. Germain, cordial de lavanda y flor de Jamaica, juniper de rosas, cinzano to sprits y bitters de naranja. El bajío, región mexica que produce la flor de Jamaica, que acompaña al St Germain, la lavanda nos transportan a un jardín floral de frescura y suaves perfumes.', 42000, 161),
('SPRITZ', 'APEROL SPRITZ', 'Aperol, cinzano to spritz , soda bretaña. Decorado con rodaja de naranja.', 28000, 162),
('TEQUILAS', 'BT.1800 CRISTALINO', null, 682000, 163),
('TEQUILAS', 'BT.1800 REPOSADO', null, 605000, 164),
('TEQUILAS', 'BT.CAZADORES REPOSADO', null, 310000, 165),
('TEQUILAS', 'BT.CENTENARIO AÑEJO', null, 473000, 166),
('TEQUILAS', 'BT.CENTENARIO REPOSADO', null, 352000, 167),
('TEQUILAS', 'BT.CLASE AZUL', null, 3200000, 168),
('TEQUILAS', 'BT.DON JULIO 1942', null, 2475000, 169),
('TEQUILAS', 'BT.DON JULIO 70', null, 825000, 170),
('TEQUILAS', 'BT.DON JULIO AÑEJO', null, 770000, 171),
('TEQUILAS', 'BT.DON JULIO BLANCO', null, 580000, 172),
('TEQUILAS', 'BT.DON JULIO CENIZA AÑEJO', null, 890000, 173),
('TEQUILAS', 'BT.DON JULIO REPOSADO', null, 682000, 174),
('TEQUILAS', 'BT.HERRADURA ULTRA', null, 682000, 175),
('TEQUILAS', 'BT.JIMADOR CRISTALINO', null, 439000, 176),
('TEQUILAS', 'BT.MAESTRO DOBEL', null, 776000, 177),
('TEQUILAS', 'BT.PATRON AÑEJO', null, 704000, 178),
('TEQUILAS', 'BT.PATRON CRISTALINO', null, 715000, 179),
('TEQUILAS', 'BT.PATRON EL CIELO', null, 2145000, 180),
('TEQUILAS', 'BT.PATRON SILVER', null, 572000, 181),
('TEQUILAS', 'TG.1800 AÑEJO', null, 52000, 182),
('TEQUILAS', 'TG.1800 CRISTALINO', null, 55000, 183),
('TEQUILAS', 'TG.1800 REPOSADO', null, 49000, 184),
('TEQUILAS', 'TG.CAZADORES CRISTALINO', null, 44000, 185),
('TEQUILAS', 'TG.CAZADORES REPOSADO', null, 34000, 186),
('TEQUILAS', 'TG.CENTENARIO AÑEJO', null, 38000, 187),
('TEQUILAS', 'TG.CLASE AZUL', null, 256000, 188),
('TEQUILAS', 'TG.DON JULIO 1942', null, 198000, 189),
('TEQUILAS', 'TG.DON JULIO 70', null, 66000, 190),
('TEQUILAS', 'TG.DON JULIO AÑEJO', null, 62000, 191),
('TEQUILAS', 'TG.DON JULIO BLANCO', null, 52000, 192),
('TEQUILAS', 'TG.DON JULIO CENIZA AÑEJO', null, 82000, 193),
('TEQUILAS', 'TG.DON JULIO REPOSADO', null, 55000, 194),
('TEQUILAS', 'TG.HERRADURA AÑEJO', null, 50000, 195),
('TEQUILAS', 'TG.HERRADURA ULTRA', null, 55000, 196),
('TEQUILAS', 'TG.JIMADOR CRISTALINO', null, 36000, 197),
('TEQUILAS', 'TG.MAESTRO DOBEL', null, 63000, 198),
('TEQUILAS', 'TG.PATRON AÑEJO', null, 57000, 199),
('TEQUILAS', 'TG.PATRON CRISTALINO', null, 58000, 200),
('TEQUILAS', 'TG.PATRON EL CIELO', null, 172000, 201),
('TEQUILAS', 'TG.PATRON SILVER', null, 46000, 202),
('VINO BLANCO', 'CP. RAMON BILBAO VERDEJO', null, 57500, 203),
('VINO ROSADO', 'CP. RAMON BILBAO', null, 57500, 204),
('VINO ROSADO', 'VR. RAMON BILBAO', null, 230000, 205),
('VINO TINTO', 'CP. RAMON BILBAO CRIANZA', null, 57500, 206),
('VINO TINTO', 'VT. LA CELIA MALBEC', null, 310000, 207),
('VINO TINTO', 'VT. MARQUES DE CASA CONCHA', null, 368000, 208),
('VINO TINTO', 'VT. RAMON BILBAO CRIANZA', null, 230000, 209),
('VINO TINTO', 'VT. RAMON BILBAO GRAN RESERVA', null, 504000, 210),
('VODKA', 'BT.GREY GOOSE', null, 500000, 211),
('VODKA', 'BT.KETEL ONE', null, 520000, 212),
('VODKA', 'BT.SMIRNOFF', null, 270000, 213),
('VODKA', 'BT.SMIRNOFF TAMARINDO', null, 280000, 214),
('VODKA', 'BT.TITOS VODKA', null, 490000, 215),
('VODKA', 'TG.GREY GOOSE', null, 46000, 216),
('VODKA', 'TG.KETEL ONE', null, 42000, 217),
('VODKA', 'TG.SMIRNOFF', null, 25000, 218),
('VODKA', 'TG.SMIRNOFF TAMARINDO', null, 16000, 219),
('VODKA', 'TG.TITOS VODKA', null, 34000, 220),
('WHISKY', 'BT.BLACK LABEL', null, 380000, 221),
('WHISKY', 'BT.BLUE LABEL', null, 2350000, 222),
('WHISKY', 'BT.BUCHANANS 12', null, 420000, 223),
('WHISKY', 'BT.BUCHANANS 18', null, 850000, 224),
('WHISKY', 'BT.BUCHANANS MASTER', null, 495000, 225),
('WHISKY', 'BT.BUCHANANS TWO SOUL', null, 550000, 226),
('WHISKY', 'BT.BULLEIT BOURBON', null, 410000, 227),
('WHISKY', 'BT.DEWARS 12', null, 378000, 228),
('WHISKY', 'BT.DEWARS 15', null, 515000, 229),
('WHISKY', 'BT.GLENFIDDICH 12', null, 460000, 230),
('WHISKY', 'BT.GLENFIDDICH 15', null, 630000, 231),
('WHISKY', 'BT.GLENFIDDICH 18', null, 970000, 232),
('WHISKY', 'BT.JACK DANIELS APPLE', null, 330000, 233),
('WHISKY', 'BT.JACK DANIELS HONEY', null, 330000, 234),
('WHISKY', 'BT.JACK DANIELS OLD 7', null, 420000, 235),
('WHISKY', 'BT.MACALLAN DOUBLE CASK 12', null, 800000, 236),
('WHISKY', 'BT.OLD PARR 12', null, 390000, 237),
('WHISKY', 'BT.SINGLETON 12', null, 430000, 238),
('WHISKY', 'TG DEWARS 12', null, 30000, 239),
('WHISKY', 'TG DEWARS 15', null, 41000, 240),
('WHISKY', 'TG.BLACK LABEL', null, 34000, 241),
('WHISKY', 'TG.BLUE LABEL', null, 188000, 242),
('WHISKY', 'TG.BUCHANANS 12', null, 33000, 243),
('WHISKY', 'TG.BUCHANANS 18', null, 63000, 244),
('WHISKY', 'TG.BUCHANANS MASTER', null, 41000, 245),
('WHISKY', 'TG.BUCHANANS TWO SOUL', null, 41000, 246),
('WHISKY', 'TG.BULLEIT BURBOUN', null, 33000, 247),
('WHISKY', 'TG.GLENFIDDICH 12', null, 48000, 248),
('WHISKY', 'TG.GLENFIDDICH 15', null, 50000, 249),
('WHISKY', 'TG.GLENFIDDICH 18', null, 76000, 250),
('WHISKY', 'TG.JACK DANIELS APPLE', null, 26000, 251),
('WHISKY', 'TG.JACK DANIELS HONEY', null, 26000, 252),
('WHISKY', 'TG.JACK DANIELS OLD 7', null, 29000, 253),
('WHISKY', 'TG.MACALLAN DOUBLE CASK 12', null, 52000, 254),
('WHISKY', 'TG.OLD PARR 12', null, 34000, 255),
('WHISKY', 'TG.SINGLETON 12', null, 37000, 256),
('ADICIONES COCINA', 'AD.ARROZ MEXICANO', null, 10000, 257),
('ADICIONES COCINA', 'AD.CALDO DE BIRRIA', null, 8000, 258),
('ADICIONES COCINA', 'AD.CARNE DE BIRRIA', null, 14000, 259),
('ADICIONES COCINA', 'AD.CHICHARRON ARTESANAL', null, 19000, 260),
('ADICIONES COCINA', 'AD.CHIPS DE PLATANO', null, 11000, 261),
('ADICIONES COCINA', 'AD.COCHINITA PIBILL', null, 15000, 262),
('ADICIONES COCINA', 'AD.ENSALADA', null, 9000, 263),
('ADICIONES COCINA', 'AD.ESQUITES', null, 14000, 264),
('ADICIONES COCINA', 'AD.GARBANZO CROCANTE', null, 0, 265),
('ADICIONES COCINA', 'AD.GUACAMOLE', null, 11000, 266),
('ADICIONES COCINA', 'AD.HELADO VAINILLA', null, 9000, 267),
('ADICIONES COCINA', 'AD.JALAPEÑOS', null, 6000, 268),
('ADICIONES COCINA', 'AD.MANI MESA', null, 0, 269),
('ADICIONES COCINA', 'AD.MAYONESA TRUFA', null, 14000, 270),
('ADICIONES COCINA', 'AD.PAPAS DOS SANTOS', null, 17000, 271),
('ADICIONES COCINA', 'AD.PICO E GALLO', null, 6000, 272),
('ADICIONES COCINA', 'AD.POLLO MEXICAN BOWL', null, 24000, 273),
('ADICIONES COCINA', 'AD.PURE DE PAPA Y SHOT DE BIRRIA', null, 15000, 274),
('ADICIONES COCINA', 'AD.QUESO CHEDDAR', null, 17000, 275),
('ADICIONES COCINA', 'AD.QUESO GRATINADO', null, 12000, 276),
('ADICIONES COCINA', 'AD.REFRITO', null, 6000, 277),
('ADICIONES COCINA', 'AD.SALSA DE AREQUIPE', null, 6000, 278),
('ADICIONES COCINA', 'AD.SALSA DE TOMATE', null, 6000, 279),
('ADICIONES COCINA', 'AD.SALSAS MESA', null, 0, 280),
('ADICIONES COCINA', 'AD.SOUR CREAM', null, 10000, 281),
('ADICIONES COCINA', 'AD.TINGA DE POLLO', null, 15000, 282),
('ADICIONES COCINA', 'AD.TORTI MAIZ', null, 11000, 283),
('ADICIONES COCINA', 'AD.TORTI MIXTA', null, 11000, 284),
('ADICIONES COCINA', 'AD.TORTILLA DE HARINA', null, 17000, 285),
('ADICIONES COCINA', 'AD.TOTOPOS', null, 12000, 286),
('ADICIONES COCINA', 'AD.TOTOPOS SOLOS', null, 8000, 287),
('ADICIONES COCINA', 'AD.VEGETALES SALTEADOS', null, 9000, 288),
('ASADOR MEXICANO', '1/2 POLLO DOS SANTOS', 'Medio pollo asado y deshuesado, marinado en yogurt griego, cocido en sous vide, mezcla de especias mexicanas, acompañado de papas criollas, pico de gallo, guacamole y sour cream.', 69000, 289),
('ASADOR MEXICANO', 'COSTILLA BBQ DE GUAYABA', 'Costilla de cerdo cocinada a baja temperatura y glaseada con salsa BBQ de guayaba. Acompañada de esquites de maíz blanco cremosos.', 91000, 290),
('ASADOR MEXICANO', 'COWBOY A LA BRASA PRIME', 'Jugoso corte de Rib Eye con hueso calidad prime (1.200 gr) pasado por nuestro asador mexicano, mantequilla de chipotle, flambeado con ron Zacapa Ámbar. Acompañado con ensalada de la casa y acompañante a elección.', 641000, 291),
('ASADOR MEXICANO', 'MAR Y TIERRA', 'Solomito y langosta parrillados, servidos con mantequilla compuesta de la casa acompañados espárragos salteados y terminados con queso Parmigiano Reggiano', 137000, 292),
('ASADOR MEXICANO', 'NEW YORK STEAK', 'Corte Premium de res New York Steak servida con mantequilla de chipotle y mazorca baby parrillada. Acompañada de nuestra ensalada de la casa y acompañante a elección.', 163000, 293),
('ASADOR MEXICANO', 'PULPO PARRILLA', 'Pulpo a la parrilla en mantequilla compuesta de la casa, acompañado de pure de papa cremoso, pico de gallo de mango y salsa de chiles ahumados.', 100000, 294),
('ASADOR MEXICANO', 'RIB EYE DE CERDO EN SALSA MOLE', 'Suave y jugoso corte de cerdo con hueso, asado a la parrilla acompañado de nuestro mole de la casa. Ensalada y acompañamiento a elección.', 79000, 295),
('ASADOR MEXICANO', 'COSTRA Y BRASA', 'Picaña de res y cerdo terminada en piedra volcanica con mantequilla de chiles, acompañada de vegetales salteados, tortilla de maiz con costra de queso, acompañado de guacamole y tomatina.', 230000, 296),
('ENSALADAS Y BOWLS', 'BOWL MEXICANO', 'Pollo marinado en yogurt griego, cubos de piña rostizada, ceviche de frijoles caraota, tomates cherry, arroz mexicano, terminado con sour cream ají dulce y cilantro.', 55000, 297),
('ENSALADAS Y BOWLS', 'CESAR SALAD CON POLLO', 'Suprema de pollo marinada en yogurt griego e hinojo terminada en nuestro asador mexicano, mix de lechugas, elotes baby parrillados, garbanzos crocante, láminas de aguacate, aderezo cesar y queso parmesano.', 52000, 298),
('ENTRADAS', 'CEVICHE DE CHICHARRON', 'Trozos de tocino ahumado marinados en leche de tigre, cebolla en plumas, cilantro, ají dulce, aguacate y mango. Acompañado con chips de plátano.', 49000, 299),
('ENTRADAS', 'CHICHARRON DE ELOTE', 'Mezcla de esquites cremosos y tentáculos mazorca, chicharrón, sour cream, Tajín, queso parmesano, brotes y flores comestibles.', 46000, 300),
('ENTRADAS', 'CHIMICHANGA', 'Tortillas de harina crocantes rellenas de suadero, chicharrón, sour cream, mermelada jalapeño, frijol refrito, queso y guacamole.', 46000, 301),
('ENTRADAS', 'EMPANADAS DE CAMARON', 'Empanada tipo taco rellena de camarones con queso, servidas con guacamole y sour cream.', 46000, 302),
('ENTRADAS', 'FLAUTAS DE TINGA DE POLLO', 'Crujientes tortillas doradas y rellenas de jugosa tinga de pollo con ese toque ahumado y ligeramente picante. Servidas con guacamole fresco, sour cream, queso fresco desmoronado y un toque de cilantro.', 41000, 303),
('ENTRADAS', 'QUESO FUNDIDO RANCHERO', 'Mezcla de quesos fundidos, chorizo artesanal, tiras de tortilla crocante, acompañado de aguacate a la parrilla tomatina con salsa de chipotle.', 57000, 304),
('ENTRADAS', 'TACOS SHOT CAMARON', 'Camarones marinados, apanados con quinua crocante; servidos sobre una copa shot, acompañado de guacamole, sour cream y salsa dos santos.', 52000, 305),
('ENTRADAS', 'TACOS SHOT RES', 'Morrillo de res braseado, terminado en nuestro asador mexicano, servido sobre una copa shot acompañado de guacamole, sour cream, salsa dos santos y pico de gallo.', 50000, 306),
('ENTRADAS', 'TACOS DE WONTON', 'Wonton Shell acompañados de camarón y langostinos en salsa de chiles ahumados. Servidos con un relish de repollo morado mango y tomate Cherry.', 42000, 307),
('ENTRADAS', 'TOSTADAS DE SALMON', 'Tortilla crocante con salmón fresco, aguacate en dos texturas, sour cream, mayonesa de chiles y un toque de tajín.', 45000, 308),
('ESPECIALES DOS SANTOS', 'ARROZ DE MARISCOS A LA TUMBADA', 'Arroz en base de salsa roja con langostinos, pulpo, calamar, camarones, mejillones, jitomate, cilantro y salsa de chipotle.', 72000, 309),
('ESPECIALES DOS SANTOS', 'CAZUELA DE MARISCOS', 'Langostinos, calamar, camarones y pulpo salteados al ajillo, en bisque cremoso de coco servido en un crocante de tortilla de harina. Acompañado con cubos de aguacate pico de gallo, queso parmesano. Acompañado de arroz mexicano.', 78000, 310),
('ESPECIALES DOS SANTOS', 'CHICHARRON DE QUESO Y SOLOMITO', 'Medallón de solomito, sobre pure de plátano acompañado de salsa de chorizo y chiles (no picante) terminado con un picadillo verde.', 77000, 311),
('ESPECIALES DOS SANTOS', 'SALMON GRILLADO', 'Salmón parrillado en mantequilla de guajillo, salsa beurre blanc sedosa, picado fresco de mango y serrano, espárragos salteados y crocante de pepita.', 85000, 312),
('PARA COMPARTIR', 'AGUACHILE DE CAMARONES', 'Camarones marinados en limón y sal, servidos con salsa de tomatillo verde, tomate, cebolla, pepino, ají dulce y aguacate.', 59000, 313),
('PARA COMPARTIR', 'FAJITAS DE COSTILLA ENCHILADA', 'Cubos de costillas doradas y caramelizadas en BBQ de guayaba y chiles servido con mix de vegetales salteados y quesos fundidos acompañada de pico de gallo y tortillas de maíz (4 und).', 72000, 314),
('PARA COMPARTIR', 'FAJITAS MIXTAS', 'Cubos de solomito de res y pechuga de pollo con cebolla y champiñones, asados y cubiertos con salsa de chile. Servidos sobre tortilla de maíz con costra de queso y acompañados de vegetales salteados.', 76000, 315),
('PARA COMPARTIR', 'GUACAMOLE DE LA CASA', 'Guacamole verde, servido con pico de gallo, ají dulce, cilantro y sour cream, acompañado con totopos.', 46000, 316),
('PARA COMPARTIR', 'MOLCAJETE MIXTO DE CARNES', 'Nuestra Mezcla perfecta de res y tocino en nuestra salsa de chiles (levemente picante). Servido sobre un molcajete con frijol refrito, sour cream, y terminado con queso gratinado guacamoles y aros de jalapeño. Acompañado de totopos o tortillas a elección.', 80000, 317),
('PARA COMPARTIR', 'NACHOS DOS SANTOS', 'Cochinita pibil, guacamole, pico de gallo, sour cream, cilantro, salsa de queso cheddar y totopos. Flameados con tequila.', 69000, 318),
('PARA COMPARTIR', 'OSOBUCO DE CERDO', 'Marinado y cocinado al vacío durante 18 horas terminado en reducción de sus propios jugos, servido con pure de papas y quesos.', 110000, 319),
('PARA COMPARTIR', 'PASTOR EN LA MESA', 'Nuestra versión de un pastor de cerdo servido en un mini horno artesanal con piña y cebolla grillados, acompañado de guacamole, sour cream pico de gallo y tortillas de maíz (8 und).', 114000, 320),
('PARA COMPARTIR', 'QUESADILLA AL PASTOR', 'Mezcla de quesos, carne al pastor, cebolla, servidas con ensalada. Acompañado de sour cream y piña parrillada.', 45000, 321),
('PARA COMPARTIR', 'QUESADILLA DE SOLOMITO', 'Mezcla de quesos, julianas de solomito de res en salsa de chiles, mayonesa de trufa, con salsa roja y guacamole. Acompañado de ensalada.', 52000, 322),
('PARA COMPARTIR', 'QUESADILLA DE TINGA DE POLLO', 'Mezcla de quesos, tinga de pollo, con pico de gallo y guacamole. Acompañado de ensalada.', 45000, 323),
('PARA COMPARTIR', 'TACADA', 'Variedad de tacos (pollo, pastor y chicharrón) taco shots de res, flautas de tinga de pollo, chimichangas y elotes.', 195000, 324),
('POSTRES', 'CHEESECAKE CON CAJETA', 'Base crujiente de galleta, relleno cremoso de queso Philadelphia y cajeta, terminado con mermelada de flor de Jamaica y fresas frescas.', 27000, 325),
('POSTRES', 'CHURROS', 'Acompañados con salsa dulce de arequipe y helado de vainilla', 27000, 326),
('POSTRES', 'CRUCIENTE TENTACION', 'Wonton apanado en galleta dulce relleno de creama de queso mascarpone terminado con crumbre de almendras mermelada de jamaica y piña fresca.', 28000, 327),
('POSTRES', 'MACETA DE CHOCOLATE', 'Suave bizcocho de vainilla remojado con rompope, salsa de yogurt griego y chocolate blanco fresas frescas y terminado con tierra y piedras de chocolate artesanal.', 34000, 328),
('TACOS', 'TACO RIB EYE 100 GR', 'Una experiencia única llevada directo a la mesa: finas láminas de Rib Eye Angus importado crudas, listas para que las selles y disfrutes en el punto de cocción que prefieras sobre un molcajete de piedra volcánica al rojo vivo. Se acompañan de tortillas de maíz con costra de queso y cuatro salsas de los Santos, que realzan el sabor intenso y jugoso de la carne.', 73000, 329),
('TACOS', 'TACO RIB EYE 200 GR', null, 137000, 330),
('TACOS', 'TACO RIB EYE 300 GR', null, 205000, 331),
('TACOS', 'TACOS AL PASTOR', 'Carne al pastor, cebolla blanca, piña, cilantro y salsa roja de la casa (2 und).', 31000, 332),
('TACOS', 'TACOS DE BIRRIA', 'Tortillas de maíz suaves y doradas, rellenas de birria de res cocida lentamente en su jugo con chiles y especias. Servidos con su tradicional consomé para sumergir, cebolla, cilantro fresco (2 und).', 39000, 333),
('TACOS', 'TACOS DE CHICHARRON', 'Chicharrón crocante, tomate cherry, frijol refrito, guacamole y salsa dos santos (2 und).', 34000, 334),
('TACOS', 'TACOS DE COCHINITA', 'Cochinita Pibill en tortilla con costra de queso, acompañada de ají dulce, jalapeño, limón mandarino.', 31000, 335),
('TACOS', 'TACOS DE POLLO', 'Pollo crispy, salsa de chipotle, aguacate, encurtido de col morada y sour cream (2 und).', 29000, 336),
('TACOS', 'TACO DE ENTRECOTE', 'Tortilla de maiz x 2 unidades con costra de queso servidos con rib eye nacional, salsa entrecote, hilos de papa salsa roja, acompañado tomatina y guacamole', 37000, 337),
('BOTANAS Y TEQUILAS', 'TACADA+1800 CRISTALINO', 'Variedad de tacos (pollo, pastor y chicharrón) taco shot''s de res, flautas de tinga de pollo, chimichangas y elotes mas una botella de 1800 cristalino', 810000, 338),
('BOTANAS Y TEQUILAS', 'TACADA+MAESTRO DOBEL', 'Variedad de tacos (pollo, pastor y chicharrón) taco shot''s de res, flautas de tinga de pollo, chimichangas y elotes mas una botella de maestro dobel', 830000, 339),
('BOTANAS Y TEQUILAS', 'DON JULIO 1942+PASTOR EN LA MESA', null, 2505000, 340),
('BOTANAS Y TEQUILAS', 'DON JULIO REPOSADO+TACOS', 'Tacos de cochinita y  tacos de pastor', 700000, 341),
('BOTANAS Y TEQUILAS', 'DON JULIO 70+NACHOS DOS SANTOS', null, 855000, 342),
('BOTANAS Y TEQUILAS', 'DON JULIO BLANCO+QUESADILLAS Y TACOS', 'Quesadilla al pastor y tacos de chicharron', 600000, 343),
('BOTANAS Y TEQUILAS', 'BUCHANANS TWO SOUL+QUESADILLA Y TACOS', 'Quesadilla al pastor y tacos de chicharron', 560000, 344),
('BOTANAS Y TEQUILAS', 'BUCHANANS 18+TACOS', 'tacos al pastor, tacos de chicharron y tacos de cochinita', 875000, 345),
('BOTANAS Y TEQUILAS', 'BUCHANANS MASTER+TACOS', 'Tacos al pastor y tacos de chicharrón', 510000, 346),
('BOTANAS Y TEQUILAS', 'JOHNNIE WALKER BLUE+PASTOR EN MESA', null, 2380000, 347),
('BOTANAS Y TEQUILAS', 'BUCHANANS 12 DELUXE+TACOS', 'tacos al pastor y tacos de chicharrón', 435000, 348),
('BOTANAS Y TEQUILAS', 'RON ZACAPA 23+TACOS', 'Tacos cochinita y tacos de pastor', 718000, 349),
('BOTANAS Y TEQUILAS', '1800 CRISTALINO+FAJITAS DE COSTILLA', null, 707000, 350),
('BOTANAS Y TEQUILAS', '1800 AÑEJO+TACOS', 'Tacos de cochinita y tacos de pastor', 667000, 351),
('BOTANAS Y TEQUILAS', '1800 REPOSADO+QUESADILLA Y TACOS', 'Quesadilla al pastor y tacos de chicharron', 625000, 352),
('BOTANAS Y TEQUILAS', '1800 SILVER+QUESADILLA Y TACOS', 'Quesadilla al pastor y tacos de chicharron', 570000, 353),
('BOTANAS Y TEQUILAS', 'MAESTRO DOBEL+TACOS', 'Tacos al pastor, tacos de chicharron y tacos de cochinita', 801000, 354),
('BOTANAS Y TEQUILAS', 'RON FLOR DE CAÑA+TACOS', 'Tacos al pastor y tacos de chicharrón', 425000, 355),
('SODAS Y JUGOS', 'J FRESA MANDARINA', null, 14000, 356),
('VINO BLANCO', 'VB.MAR DE FRADES ALBARIÑO', null, 320000, 357),
('VINO BLANCO', 'VB.RAMON BILBAO VERDEJO', null, 230000, 358),
('COCTELERIA CLASICA', 'PISCO SOUR', null, 45000, 359),
('COCTELERIA CLASICA', 'CANTARITO', null, 48000, 360)
) as v(categoria, nombre, descripcion, precio, orden)
where l.slug = 'dos-santos'
on conflict (location_id, categoria, nombre) do update
  set descripcion = excluded.descripcion, precio = excluded.precio, orden = excluded.orden;
